


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Boris
 */
public class configPro1 extends javax.swing.JFrame {

    /**
     * Creates new form EjPract1
     */
    public configPro1() {
        initComponents();
        
        cboPai.addItem("Ecuador");
        cboPai.addItem("Colombia");
        cboPai.addItem("Argentina");
        
       
       
       cboPai.setSelectedItem(ProperPais());
       cboCiu.setSelectedItem(ProperCiudad());
       
       switch (ProperEstadoCivil())
                    {
                        case "Casado":
                            rbCas.setSelected(true);
                            break;
                        case "Divorciado":
                            rbDiv.setSelected(true);
                            break;
                        case "Soltero":
                            rbSolt.setSelected(true);
                            break;
                        case "Viudo":
                            rbViu.setSelected(true);
                            break;
                    }
       

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboPai = new javax.swing.JComboBox<>();
        cboCiu = new javax.swing.JComboBox<>();
        rbSolt = new javax.swing.JRadioButton();
        rbCas = new javax.swing.JRadioButton();
        rbViu = new javax.swing.JRadioButton();
        rbDiv = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pais:");

        jLabel2.setText("Ciudad:");

        cboPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPaiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbSolt);
        rbSolt.setText("Soltero");

        buttonGroup1.add(rbCas);
        rbCas.setText("Casado");

        buttonGroup1.add(rbViu);
        rbViu.setText("Viudo");

        buttonGroup1.add(rbDiv);
        rbDiv.setText("Divorciado");

        jLabel3.setText("Estado Civil:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboPai, 0, 184, Short.MAX_VALUE)
                    .addComponent(cboCiu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbDiv)
                    .addComponent(rbViu)
                    .addComponent(rbCas)
                    .addComponent(rbSolt))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboCiu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(rbSolt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCas)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbViu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbDiv)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPaiActionPerformed
        
        
        
        
        switch (cboPai.getSelectedIndex())
        {
            case 0:
                     cboCiu.removeAllItems();
                     cboCiu.addItem("Guayaquil");
                     cboCiu.addItem("Quito");
                     cboCiu.addItem("Cuenca");
                     
                    break;
            case 1:
                     cboCiu.removeAllItems();
                     cboCiu.addItem("Cali");
                     cboCiu.addItem("Bogota");
                     cboCiu.addItem("Armenia");
                     break;
            case 2:
                     cboCiu.removeAllItems();
                     cboCiu.addItem("Buenos Aires");
                     cboCiu.addItem("Mendoza");
                     cboCiu.addItem("Salta");
                     break; 
            default:
        }
    }//GEN-LAST:event_cboPaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(configPro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(configPro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(configPro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(configPro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new configPro1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboCiu;
    private javax.swing.JComboBox<String> cboPai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton rbCas;
    private javax.swing.JRadioButton rbDiv;
    private javax.swing.JRadioButton rbSolt;
    private javax.swing.JRadioButton rbViu;
    // End of variables declaration//GEN-END:variables

private String ProperEstadoCivil()
{
        String strRes="";
        try
        {
            //Leer archivo de configuración .
            java.util.Properties proArc=new java.util.Properties();
            
            java.io.FileInputStream fis=new java.io.FileInputStream("config.properties.txt");
            proArc.load(fis);
            fis.close();
            
            
            
            strRes=proArc.getProperty("EstadoCivil");
            proArc=null;
        }
        catch (java.io.IOException e)
        {
            strRes="";
        }
        catch (Exception e)
        {
            strRes="";
        }
        return strRes;
    }     
 
private String ProperCiudad()
{
        String strRes2="";
        try
        {
            //Leer archivo de configuración .
            java.util.Properties proArc=new java.util.Properties();
            
            java.io.FileInputStream fis=new java.io.FileInputStream("config.properties.txt");
            proArc.load(fis);
            fis.close();
            
            strRes2=proArc.getProperty("Ciudad");
            
            
            
            proArc=null;
        }
        catch (java.io.IOException e)
        {
            strRes2="";
        }
        catch (Exception e)
        {
            strRes2="";
        }
        return strRes2;
    }    
private String ProperPais()
{
        String strRes1="";
        try
        {
            //Leer archivo de configuración .
            java.util.Properties proArc=new java.util.Properties();
            
            java.io.FileInputStream fis=new java.io.FileInputStream("config.properties.txt");
            proArc.load(fis);
            fis.close();
            
            strRes1=proArc.getProperty("Pais");
            
            
            
            proArc=null;
        }
        catch (java.io.IOException e)
        {
            strRes1="";
        }
        catch (Exception e)
        {
            strRes1="";
        }
        return strRes1;
    }     
   

}
