


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Boris
 */
public class EjercicioDeberPais extends javax.swing.JFrame {

    /**
     * Creates new form EjPract1
     */
    public EjercicioDeberPais() {
        initComponents();
        
        cboPai.addItem("Ecuador");
        cboPai.addItem("Colombia");
        cboPai.addItem("Argentina");
        cboPai.setSelectedIndex(-1);
        
     
        
       cboCiu.setSelectedIndex(-1);
       
          cboDep.removeAllItems();
           cboDep.addItem("Jumping");
           cboDep.addItem("Raffing");
           cboDep.addItem("Paracaidismo");
                
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        butReg = new javax.swing.JButton();
        cboPai = new javax.swing.JComboBox<>();
        cboCiu = new javax.swing.JComboBox<>();
        txtNom = new javax.swing.JTextField();
        txtEd = new javax.swing.JTextField();
        cboDep = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pais:");

        jLabel2.setText("Ciudad:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Edad:");

        jLabel5.setText("Deportes:");

        butReg.setText("Registrar");
        butReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRegActionPerformed(evt);
            }
        });

        cboPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPaiActionPerformed(evt);
            }
        });

        cboDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboPai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboCiu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNom)
                            .addComponent(txtEd, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboDep, 0, 184, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(butReg)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboCiu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(butReg)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPaiActionPerformed
        
        
        
        
        switch (cboPai.getSelectedIndex())
        {
            case 0:
                     cboCiu.removeAllItems();
                     cboCiu.addItem("Guayaquil");
                     cboCiu.addItem("Quito");
                     cboCiu.addItem("Cuenca");
                     
                    break;
            case 1:
                     cboCiu.removeAllItems();
                     cboCiu.addItem("Cali");
                     cboCiu.addItem("Bogota");
                     cboCiu.addItem("Armenia");
                     break;
            case 2:
                     cboCiu.removeAllItems();
                     cboCiu.addItem("Buenos Aires");
                     cboCiu.addItem("Mendoza");
                     cboCiu.addItem("Salta");
                     break; 
            default:
        }
    }//GEN-LAST:event_cboPaiActionPerformed

    private void butRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRegActionPerformed
        
        String Nom, Pai, Ciu, Ed=null, Dep, Dat;
        Nom=txtNom.getText();
        Pai=cboPai.getSelectedItem().toString();
        Ciu=cboCiu.getSelectedItem().toString();
        Dep=cboDep.getSelectedItem().toString();
        
        int Eda;
        Eda=Integer.parseInt(txtEd.getText());
        
        if (Eda<=12 || Eda>=30)
        {
            JOptionPane.showMessageDialog(this, "Error Edad no permitida.");
            return;
        }
        switch (cboDep.getSelectedIndex())
        {
        case 0:
        
        if (Eda>=13 && Eda<=18)
        {
        Dat=Nom+"-"+Pai+"-"+Ciu+"-"+" Se Registro en: "+Dep;
        JOptionPane.showMessageDialog(this, Dat);
        return;
        }
        else if (Eda>=19 && Eda<=24 )
        {
            Dat=Nom+"-"+Pai+"-"+Ciu+"-"+" Se Registro en: "+Dep;
        JOptionPane.showMessageDialog(this, Dat);
        return;
        }
        else if (Eda>=25 && Eda<=30)
        {
           Dat=Nom+"-"+Pai+"-"+Ciu+"-"+" Se Registro en: "+Dep;
        JOptionPane.showMessageDialog(this, Dat);
        return; 
        }
        
        case 1:
        
        if (Eda>=19 && Eda<=24 )
        {
           Dat=Nom+"-"+Pai+"-"+Ciu+"-"+" Se Registro en: "+Dep;
        JOptionPane.showMessageDialog(this, Dat);
        return;  
        }
        
        
        
       
        case 2:
        
        if (Eda>=25 && Eda<=30)
        {
        Dat=Nom+"-"+Pai+"-"+Ciu+"-"+" Se Registro en: "+Dep;
        JOptionPane.showMessageDialog(this, Dat);
        
        }
        else 
        {
            JOptionPane.showMessageDialog(this, "Error Deporte fuera de rango");
        }
        
        
        
            
       
        
       
        
        
        
        
        
        
        
        }
        
    }//GEN-LAST:event_butRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjercicioDeberPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjercicioDeberPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjercicioDeberPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjercicioDeberPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjercicioDeberPais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butReg;
    private javax.swing.JComboBox<String> cboCiu;
    private javax.swing.JComboBox<String> cboDep;
    private javax.swing.JComboBox<String> cboPai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtEd;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
